insert into public.products (
  slug,
  name,
  brand,
  category,
  subcategory,
  description,
  short_description,
  composition,
  effects,
  skin_types,
  skin_problems,
  price,
  wholesale_price,
  volume,
  image_url,
  in_stock,
  featured,
  new_arrival,
  bestseller,
  usage_instructions,
  country_of_origin
)
values
  (
    'hydrating-cleanser',
    'Hydrating Cleanser',
    'YUVEMA Lab',
    'Очищение',
    'Гель',
    'Мягкое ежедневное очищение без пересушивания.',
    'Очищающий гель для чувствительной и обезвоженной кожи.',
    'Ниацинамид, алоэ вера, мягкие ПАВы',
    'Снимает загрязнения и поддерживает гидролипидный баланс.',
    array['Сухая', 'Чувствительная', 'Комбинированная'],
    array['Сухость', 'Покраснения'],
    12500,
    9800,
    '200 мл',
    'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900',
    true,
    true,
    true,
    false,
    'Использовать утром и вечером на влажной коже.',
    'Корея'
  ),
  (
    'clarity-serum',
    'Clarity Serum',
    'YUVEMA Clinical',
    'Сыворотка',
    'Сыворотка',
    'Сыворотка с себорегулирующим и выравнивающим действием.',
    'Снижает воспаления и визуально выравнивает тон кожи.',
    'Ниацинамид, цинк, пантенол',
    'Снимает покраснения и помогает при несовершенствах.',
    array['Жирная', 'Комбинированная', 'Чувствительная'],
    array['Акне', 'Покраснения', 'Расширенные поры'],
    16800,
    13200,
    '30 мл',
    'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=900',
    true,
    true,
    false,
    true,
    'Наносить после очищения и тонизации 1-2 раза в день.',
    'Франция'
  ),
  (
    'barrier-cream',
    'Barrier Recovery Cream',
    'YUVEMA Derma',
    'Крем',
    'Крем',
    'Восстанавливающий крем для укрепления защитного барьера кожи.',
    'Питательный крем с комфортной текстурой для сухой и чувствительной кожи.',
    'Церамиды, сквалан, пантенол',
    'Уменьшает сухость, стянутость и повышает комфорт кожи.',
    array['Сухая', 'Чувствительная', 'Нормальная'],
    array['Сухость', 'Покраснения', 'Морщины'],
    18200,
    14500,
    '50 мл',
    'https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?w=900',
    true,
    false,
    false,
    true,
    'Наносить завершающим этапом ухода утром и вечером.',
    'Испания'
  ),
  (
    'daily-spf50',
    'Daily UV Shield SPF 50',
    'YUVEMA Solar',
    'Защита',
    'SPF',
    'Ежедневная защита от UVA/UVB для городского режима.',
    'Лёгкий солнцезащитный крем без липкости и белого следа.',
    'Химические и минеральные фильтры, витамин Е',
    'Предотвращает фотостарение и защищает от пигментации.',
    array['Сухая', 'Жирная', 'Комбинированная', 'Нормальная', 'Чувствительная'],
    array['Пигментация', 'Морщины', 'Покраснения'],
    14900,
    11900,
    '50 мл',
    'https://images.unsplash.com/photo-1619451334792-150fd785ee74?w=900',
    true,
    false,
    true,
    true,
    'Наносить утром последним этапом ухода и обновлять каждые 2-3 часа.',
    'Япония'
  )
on conflict (slug) do update
set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  short_description = excluded.short_description,
  composition = excluded.composition,
  effects = excluded.effects,
  skin_types = excluded.skin_types,
  skin_problems = excluded.skin_problems,
  price = excluded.price,
  wholesale_price = excluded.wholesale_price,
  volume = excluded.volume,
  image_url = excluded.image_url,
  in_stock = excluded.in_stock,
  featured = excluded.featured,
  new_arrival = excluded.new_arrival,
  bestseller = excluded.bestseller,
  usage_instructions = excluded.usage_instructions,
  country_of_origin = excluded.country_of_origin;

insert into public.blog_posts (
  slug,
  title,
  excerpt,
  content,
  cover_image,
  category,
  tags,
  published
)
values
  (
    'summer-spf-guide',
    'Как подобрать SPF на каждый день',
    'Краткий гид по выбору ежедневной солнцезащиты для города и отдыха.',
    '## Почему SPF нужен круглый год\n\nСолнцезащита снижает риск фотостарения, пигментации и реактивности кожи.\n\n## На что смотреть\n\n- SPF 30+ для города\n- SPF 50 для активного солнца\n- Комфортная текстура, которую вы готовы использовать ежедневно',
    'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1200',
    'Уход',
    array['spf', 'summer', 'skin-care'],
    true
  ),
  (
    'hydration-vs-nutrition',
    'Увлажнение и питание: в чём разница',
    'Разбираем, когда коже нужен увлажняющий гель, а когда — восстанавливающий крем.',
    '## Увлажнение\n\nУвлажняющие средства работают с водой и удержанием влаги.\n\n## Питание\n\nПитательные формулы восстанавливают барьер и уменьшают чувство стянутости.\n\n## Как сочетать\n\nНачните с сыворотки, затем закрепите результат кремом по типу кожи.',
    'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=1200',
    'Экспертиза',
    array['hydration', 'barrier', 'routine'],
    true
  )
on conflict (slug) do update
set
  title = excluded.title,
  excerpt = excluded.excerpt,
  content = excluded.content,
  cover_image = excluded.cover_image,
  category = excluded.category,
  tags = excluded.tags,
  published = excluded.published;

